### ISSUE TITLE
Fix the version

### ISSUE THREAD

**Issue by skupr-anaconda** [conda-incubator/conda-auth#25]
### What happened?

You have released v0.2.0 but the source code still has `0.1.0` https://github.com/conda-incubator/conda-auth/blob/ac0d996f015f05c3dd1307ca095abcf22af30b1a/pyproject.toml#L7

**Comment by travishathaway** [comment]
I think I will just created a new release `0.2.1` that fixes the version number. I do not want to edit the current `0.2.0` release considering that it is already on conda-forge.

**Comment by travishathaway** [comment]
I believe this commit will solve this problem going forward:

https://github.com/conda-incubator/conda-auth/commit/39d99796291220d1e65e2195e6a3a3b4fbad23c5

**Comment by travishathaway** [comment]
@skupr-anaconda,

I decided to go with hatchling instead to copy what conda-libmamba-solver and conda do. I have updated both `pyproject.toml` and `recipe/meta.yml`.

**Comment by skupr-anaconda** [comment]
Thank you!
