### ISSUE TITLE
Expand developer contribution docs with conda-native workflow

### ISSUE THREAD

**Issue by jezdez** [conda-incubator/conda-auth#35]
### What is the idea?

To lower the barrier of entry for contributors that don't have pixi installed on their machine, let's expand the [contributing docs](https://conda-incubator.github.io/conda-auth/dev/) in the Developer Guide to list a conda-only way as well (favoribly as the first item in the list of options).

### Why is this needed?

Lower barrier for contribution for conda users.

### What should happen?

I would suggest to use conda-project (if we want to retain a project management focus), conda-lock (for reproducible environemts) or simply a plain conda environment.yml. Maybe we can also look at other conda incubated projects to follow precedence.

**Comment by travishathaway** [comment]
Let's add an `environment.yml` to the repository and add documentation for how to create a development environment using it.

**Comment by travishathaway** [comment]
@jezdez,

Please see the following pull request:

- #36
